#端口
server:  port: '@server.demo.port@'

  
spring:  application:    name: itour-demo-web
  profiles:
    active: '@profiles.active@'
  datasource: #mysql的配置
    url: '@spring.datasource.url@'
    driver-class-name: '@spring.datasource.driverClassName@'
    username: '@spring.datasource.username@'
    password: '@spring.datasource.password@'
#eureka
eureka:
  client:
    service-url:
      defaultZone: http://@eureka.host@:@server.eureka.port@/eureka
  instance:
    prefer-ip-address: '@eureka.instance.prefer-ip-address@'  
#beetl
beetl:
  templatesPath: /templates/   
  
ribbon: 
  ConnectTimeout: '@ribbon.ConnectTimeout@'  #请求连接的超时时间 默认的时间为 1 秒
  ReadTimeout: '@ribbon.ReadTimeout@'     #请求处理的超时时间
  MaxAutoRetries: '@ribbon.MaxAutoRetries@'      #解决fegin超时重试多条数据插入数据库问题
  MaxAutoRetriesNextServer: '@ribbon.MaxAutoRetriesNextServer@'  #解决fegin超时重试多条数据插入数据库问题
 
feign:
  client:
    config:
      default:
        connect-timeout: '@feign.client.config.default.connect-timeout@'
        read-timeout: '@feign.client.config.default.read-timeout@'  
        
mybatis-plus:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.itour.model
  configuration:
    map-underscore-to-camel-case: true  