#2021-02-03 wangtao
#后台t_m_group初始化
INSERT INTO T_M_GROUP ( G_NAME, G_DESC, G_PARENT,CREATEDATE )
VALUES( 'GSAdmin', '超级管理员组', '0',1610157163369 );	
INSERT INTO T_M_GROUP ( G_NAME, G_DESC, G_PARENT,CREATEDATE )
VALUES( 'Gadmin', '管理员组', '0',1610157163369 );
INSERT INTO T_M_GROUP ( G_NAME, G_DESC, G_PARENT,CREATEDATE )
VALUES( 'Gnormal', '普通会员组', '0',1610157163369 );

#后台t_m_role初始化
INSERT INTO T_M_ROLE (ROLE_NAME, ROLE_DESC,CREATEDATE)
VALUES('Rnormal', '普通用户',1610157163369);
INSERT INTO T_M_ROLE (ROLE_NAME, ROLE_DESC,CREATEDATE)
VALUES('RSAdmin','超级管理员',1610157163369);
INSERT INTO T_M_ROLE (ROLE_NAME, ROLE_DESC,CREATEDATE)
VALUES('RNAdmin','普通管理员',1610157163369);





#2020-7-3 wangtao 
#前台t_a_group初始化
INSERT INTO T_A_GROUP ( G_NAME, G_DESC, G_PARENT,CREATEDATE)
VALUES
	( 'Gnormal', '普通会员组', '0' ,1610157163369);
INSERT INTO T_A_GROUP ( G_NAME, G_DESC, G_PARENT,CREATEDATE )
VALUES
	( 'Gvip', 'VIP会员组', '0',1610157389885 );
	
#前台t_a_role初始化	
INSERT INTO T_A_ROLE( ROLE_NAME, ROLE_DESC ) 
VALUES( 'Rnormal', '普通用户' );

INSERT INTO T_A_ROLE( ROLE_NAME, ROLE_DESC ) 
VALUES( 'Rvip', 'VIP用户' );
	
INSERT INTO T_A_ROLE( ROLE_NAME, ROLE_DESC ) 
VALUES( 'RSAdmin', '超级管理员' );

INSERT INTO T_A_ROLE( ROLE_NAME, ROLE_DESC ) 
VALUES( 'RNAdmin', '普通管理员' );




#-前台旅行信息专栏表
INSERT INTO T_T_TRAVEL_COLUMN(`COLUMN`,UID,CREATEDATE)VALUES('旅行攻略','10000','1596506073');
INSERT INTO T_T_TRAVEL_COLUMN(`COLUMN`,UID,CREATEDATE)VALUES('周末攻略','10000','1596506073');
INSERT INTO T_T_TRAVEL_COLUMN(`COLUMN`,UID,CREATEDATE)VALUES('vlog','10000','1596506073');



#地址信息 http://www.loglogo.com/front/countryCode/
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('上海','3100','-1','1');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('上海市','3101','3100','2');

insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('江苏省','3200','-1','1');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('南京市','3201','3200','2');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('无锡市','3202','3200','2');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('徐州市','3203','3200','2');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('常州市','3204','3200','2');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('苏州市','3205','3200','2');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('南通市','3206','3200','2');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('连云港市','3207','3200','2');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('盐城市','3209','3200','2');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('扬州市','3210','3200','2');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('镇江市','3211','3200','2');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('泰州市','3212','3200','2');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('宿迁市','3213','3200','2');

insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('浙江省','3300','-1','1');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('杭州市','3301','3300','2');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('宁波市','3302','3300','2');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('温州市','3303','3300','2');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('嘉兴市','3304','3300','2');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('湖州市','3305','3300','2');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('绍兴市','3306','3300','2');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('金华市','3307','3300','2');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('衢州市','3308','3300','2');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('舟山市','3309','3300','2');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('台州市','3310','3300','2');
insert into T_T_REGION(REGION_NAME,REGION_CODE,REGION_PARENT_ID,REGION_LEVEL)
VALUES('丽水市','3311','3300','2');


