#端口号
server:  port: '@server.online-manager.port@'
  servlet:
    context-path: /manager
spring:  profiles:    active: '@profiles.active@' #指定激活环境
  application:    name: itour-online-manager-web #指定项目名称#eureka
eureka:  client:    service-url:      defaultZone: http://@eureka.host@:@server.eureka.port@/eureka  
  instance:
    prefer-ip-address: '@eureka.instance.prefer-ip-address@'   
      
#beetl
beetl:
  templatesPath: /templates/
#全局配置 

ribbon: 
  ConnectTimeout: '@ribbon.ConnectTimeout@'  #请求连接的超时时间 默认的时间为 1 秒
  ReadTimeout: '@ribbon.ReadTimeout@'     #请求处理的超时时间
  MaxAutoRetries: '@ribbon.MaxAutoRetries@'      #解决fegin超时重试多条数据插入数据库问题
  MaxAutoRetriesNextServer: '@ribbon.MaxAutoRetriesNextServer@'  #解决fegin超时重试多条数据插入数据库问题

  
feign:
  client:
    config:
      default:
        connect-timeout: '@feign.client.config.default.connect-timeout@'
        read-timeout: '@feign.client.config.default.read-timeout@'  