#端口 https://blog.csdn.net/HXNLYW/article/details/95055601
server:  port: '@server.quartz.port@'
#项目名称
spring:
  profiles:
    active: '@profiles.active@'  application:    name: itour-quartz-service
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          url: '@spring.datasource.url@'
          driver-class-name: '@spring.datasource.driverClassName@'
          username: '@spring.datasource.username@'
          password: '@spring.datasource.password@'
        quartz:
          url: '@spring.datasource.url@'
          driver-class-name: '@spring.datasource.driverClassName@'
          username: '@spring.datasource.username@'
          password: '@spring.datasource.password@'
  # quartz定时任务
  quartz:
    jdbc:
      # 初始化Quartz表结构,项目第一次启动配置程always,然后改成never 否则已生成的job会被初始化掉
      initialize-schema: always
    #设置quartz任务的数据持久化方式，默认是内存方式
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: etlCleanScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_  #Quartz表前缀
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            #线程数 一个任务使用一个线程
            threadCount: 100
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true  redis:     #reids相关配置
    database: '@spring.redis.database@'    host: '@spring.redis.host@'    port: '@spring.redis.port@'
    password: '@spring.redis.password@'
    jedis:      max-active: '@spring.redis.pool.max-active@'
      max-wait: '@spring.redis.pool.max-wait@'
      max-idle: '@spring.redis.pool.max-idle@'
      min-idle: '@spring.redis.pool.min-idle@'
    timeout: '@spring.redis.timeout@'
  
#eureka
eureka:  client:    service-url:      defaultZone: http://@eureka.host@:@server.eureka.port@/eureka
#mybatis plus
mybatis-plus:  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.itour.model.quartz
  configuration:
    map-underscore-to-camel-case: true
#log
logging:
  level:
    com: 
      itour:
        persist: '@logging.level@'