#端口号
server:  port: '@server.online.port@'  servlet:    context-path: /itour
spring:  profiles:    active: '@profiles.active@' #指定激活环境
  application:    name: itour-online-web #指定项目名称
  redis:     #reids相关配置单元测试的时候需要用到此配置
    database: '@spring.redis.database@'
    host: '@spring.redis.host@'
    port: '@spring.redis.port@'
    password: '@spring.redis.password@'
    jedis:
      pool:
        max-active: '@spring.redis.pool.max-active@'
        max-wait: '@spring.redis.pool.max-wait@'
        max-idle: '@spring.redis.pool.max-idle@'
        min-idle: '@spring.redis.pool.min-idle@'
    timeout: '@spring.redis.timeout@'#eureka
eureka:  client:    service-url:      defaultZone: http://@eureka.host@:@server.eureka.port@/eureka      instance:    prefer-ip-address: '@eureka.instance.prefer-ip-address@'
      
#beetl
beetl:
  templatesPath: /templates/
#ribbon全局配置 

ribbon: 
  ConnectTimeout: '@ribbon.ConnectTimeout@'  #请求连接的超时时间 默认的时间为 1 秒
  ReadTimeout: '@ribbon.ReadTimeout@'     #请求处理的超时时间
  MaxAutoRetries: '@ribbon.MaxAutoRetries@'      #解决fegin超时重试多条数据插入数据库问题
  MaxAutoRetriesNextServer: '@ribbon.MaxAutoRetriesNextServer@'  #解决fegin超时重试多条数据插入数据库问题
#fegin
feign:
  client:
    config:
      default:
        connect-timeout: '@feign.client.config.default.connect-timeout@'
        read-timeout: '@feign.client.config.default.read-timeout@'
#文件上传配置
upload:
  location: '@fileupload.path@'
  resourceHandler: /uploaded/**   #请求 url 中的资源映射
#log    
logging:
  path: '@log.home@'
#FastDFS
#fdfs:#  so-timeout: '@fdfs.so-timeout@' #socket连接超时时长
#  connect-timeout: '@fdfs.connect-timeout@' #连接tracker服务器超时时长
#  thumb-image: #   width: '@fdfs.thumb-image.width@'
 #   height: '@fdfs.thumb-image.height@'
  #etracker-list: '@fdfs.tracker-list@' 